# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 558674c857cccf9ddc2e4dc81b0b154fa83bbe8f475f57f1df000e21d04758208b0de07bf565aca440a893391955fb977c270c7b883e04ed849715d130a2b4ce

test:
  secret_key_base: be616ec4bbbb5fdaef72c523f0ba0a87c5585e63118f61e5f662adaa47dec733a36225ffddcd3f1e93c200905941ffd979657ca9caddb8902145ab6e617ab6e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
